export function convertToHTML(metadata: any, references: any[] = [], figures: any[] = []) {
  // A clean, stylized HTML representation of the extracted metadata and article contents.
  return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${metadata.title || 'Research Article'}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 40px; color: #333; }
        h1 { color: #0A2540; font-size: 2.5em; border-bottom: 2px solid #2ECC71; padding-bottom: 10px; }
        h2 { color: #0A2540; margin-top: 40px; }
        .abstract { background: #f9f9f9; padding: 20px; border-left: 4px solid #2ECC71; margin-bottom: 30px; }
        .keywords { font-weight: bold; color: #555; }
        .figure { text-align: center; margin: 30px 0; }
        .figure img { max-width: 100%; border: 1px solid #ddd; padding: 5px; }
        .caption { font-size: 0.9em; color: #666; margin-top: 10px; font-style: italic; }
        .reference-list { list-style-type: decimal; padding-left: 20px; }
        .reference-list li { margin-bottom: 10px; }
        footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 0.8em; text-align: center; color: #777; }
    </style>
</head>
<body>
    <header>
        <h1>${metadata.title || 'Untitled Article'}</h1>
    </header>

    ${metadata.abstract ? `
    <section class="abstract">
        <h2>Abstract</h2>
        <p>${metadata.abstract}</p>
        ${metadata.keywords ? `<p class="keywords">Keywords: ${metadata.keywords}</p>` : ''}
    </section>
    ` : ''}

    <section class="figures">
        ${figures.length > 0 ? '<h2>Figures</h2>' : ''}
        ${figures.map(f => `
            <div class="figure">
                <img src="${f.base64Data}" alt="${f.caption}" />
                <div class="caption">${f.label}: ${f.caption}</div>
            </div>
        `).join('')}
    </section>

    <section class="references">
        ${references.length > 0 ? '<h2>References</h2><ol class="reference-list">' : ''}
        ${references.map(r => `
            <li>
                ${r.rawText}
                ${r.doi ? `<br/><a href="https://doi.org/${r.doi}" target="_blank">doi:${r.doi}</a>` : ''}
            </li>
        `).join('')}
        ${references.length > 0 ? '</ol>' : ''}
    </section>

    <footer>
        <p>Generated by Automated JATS XML Conversion Platform &copy; 2026 Softsols Pakistan</p>
    </footer>
</body>
</html>
  `.trim();
}
